version: '3'
services:
  postgres:
      image: products-postgres-db
      network_mode: bridge
      container_name: postgres 
      restart: unless-stopped
  server:
      image: products-server-java
      container_name: server
      network_mode: bridge
      ports:
        - "8080:8080"   
      restart: unless-stopped
      depends_on:
        - postgres
      links:
        - postgres
      