FROM node:11.13.0

# install chrome for protractor tests
#RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#RUN apt-get update && apt-get install -yq google-chrome-stable

WORKDIR /app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

ENV PATH /app/node_modules/.bin:$PATH


COPY package.json /app/package.json
RUN npm install


COPY . /app


CMD npm start -- --p 4321

EXPOSE 4321

# docker run -v ${PWD}:/app -v /app/node_modules -p 4321:4321 --rm example:dev